### ISSUE TITLE
Update "Step by step guide to view the slides locally"

### ISSUE THREAD

**Issue by sswastik02** [RedHatOfficial/GoCourse#163]
The installation instructions in the [README](https://github.com/RedHatOfficial/GoCourse?tab=readme-ov-file#step-by-step-guide-to-view-the-slides-locally) specifies using:
```
go install golang.org/x/tools/cmd/present
```

However this errors out with the following output:
```
$ go install golang.org/x/tools/cmd/present
no required module provides package golang.org/x/tools/cmd/present; to add it:
        go get golang.org/x/tools/cmd/present
```

However running `go get` succeeds, and then `./presentation.sh` works as expected

If you think this is valid, I am more than happy to submit a PR for the same.

**Comment by tisnik** [comment]
hi @sswastik02 . yes, it is valid, please create a PR if you will. Thank you in advance!
